name: CI and Release

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build-test-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: cd build && ctest --output-on-failure

      - name: Create DEB package
        run: cd build && cpack -G DEB

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: weatherapp
          path: build/*.deb

  release:
    needs: build-test-package
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Download DEB artifact
        uses: actions/download-artifact@v4
        with:
          name: weatherapp
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.deb"
