name: CMake Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      - name: Configure CMake
        run: mkdir build && cd build && cmake ..
      - name: Build
        run: cd build && cmake --build .
      - name: Test
        run: cd build && ctest --output-on-failure
      - name: Package
        run: cd build && cpack -G DEB
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weatherapp-deb
          path: build/*.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: weatherapp-deb
          path: .
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: "*.deb"
